import { StyleSheet } from 'react-native';
import { Platform, StatusBar, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');
const cardWidth = width * 0.18;
const cardHeight = cardWidth * 1.4;

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#0C3B0C', // Verde escuro de mesa de blackjack
        paddingTop: Platform.OS === 'ios' ? 50 : StatusBar.currentHeight + 20,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        marginBottom: 10,
    },
    backButton: {
        padding: 10,
    },
    title: {
        flex: 1,
        fontSize: 20,
        fontWeight: 'bold',
        color: '#FFD700',
        textAlign: 'center',
    },
    roomStatus: {
        backgroundColor: '#333',
        paddingVertical: 4,
        paddingHorizontal: 10,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#FFD700',
    },
    roomStatusText: {
        color: '#FFD700',
        fontSize: 12,
        fontWeight: 'bold',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        color: '#FFF',
        marginTop: 10,
        fontSize: 16,
    },
    gameContainer: {
        flex: 1,
        padding: 10,
    },
    dealerSection: {
        alignItems: 'center',
        marginBottom: 20,
    },
    dealerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#FFF',
        marginBottom: 10,
    },
    dealerCards: {
        flexDirection: 'row',
        justifyContent: 'center',
        minHeight: cardHeight,
    },
    waitingDealer: {
        width: cardWidth * 2,
        height: cardHeight,
        backgroundColor: 'rgba(0,0,0,0.3)',
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#555',
    },
    roundStatus: {
        backgroundColor: 'rgba(0,0,0,0.5)',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 20,
        alignItems: 'center',
        marginVertical: 10,
    },
    roundStatusText: {
        color: '#FFF',
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: 5,
    },
    resultText: {
        fontSize: 18,
        fontWeight: 'bold',
        textAlign: 'center',
        marginTop: 5,
    },
    resultWon: {
        color: '#4CAF50',
    },
    resultLost: {
        color: '#F44336',
    },
    resultDraw: {
        color: '#2196F3',
    },
    playersSection: {
        flex: 1,
    },
    playerContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.3)',
        borderRadius: 10,
        padding: 10,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#444',
    },
    activePlayer: {
        borderColor: '#FFD700',
        backgroundColor: 'rgba(255, 215, 0, 0.1)',
    },
    playerInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    playerAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#333',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    playerName: {
        color: '#FFF',
        fontSize: 16,
        fontWeight: 'bold',
        flex: 1,
    },
    playerCards: {
        flexDirection: 'row',
        minHeight: cardHeight * 0.8,
        alignItems: 'center',
    },
    waitingContainer: {
        width: cardWidth,
        height: cardHeight * 0.8,
        backgroundColor: 'rgba(0,0,0,0.3)',
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#555',
    },
    waitingText: {
        color: '#999',
        fontSize: 12,
        textAlign: 'center',
    },
    gameControls: {
        marginTop: 20,
        marginBottom: Platform.OS === 'ios' ? 30 : 20,
    },
    betButton: {
        flexDirection: 'row',
        backgroundColor: '#FFD700',
        padding: 15,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
    },
    betButtonText: {
        color: '#000',
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 10,
    },
    actionButtons: {
        flexDirection: 'row',
        justifyContent: 'space-around',
    },
    actionButton: {
        backgroundColor: '#FFD700',
        padding: 12,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        flex: 1,
        marginHorizontal: 5,
        maxWidth: 80,
    },
    actionButtonText: {
        color: '#000',
        fontSize: 14,
        fontWeight: 'bold',
        marginTop: 5,
    },
    waitingTurn: {
        padding: 15,
        borderRadius: 10,
        backgroundColor: 'rgba(0,0,0,0.5)',
        alignItems: 'center',
    },
    waitingTurnText: {
        color: '#FFF',
        fontSize: 16,
    },
    card: {
        width: cardWidth,
        height: cardHeight,
        backgroundColor: '#FFF',
        borderRadius: 8,
        position: 'relative',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#DDD',
        shadowColor: '#000',
        shadowOffset: { width: 1, height: 1 },
        shadowOpacity: 0.3,
        shadowRadius: 2,
        elevation: 3,
    },
    cardBack: {
        backgroundColor: '#209CEE',
    },
    cardPattern: {
        transform: [{ rotate: '45deg' }],
    },
    cardCorner: {
        position: 'absolute',
        top: 5,
        left: 5,
        fontSize: 14,
        fontWeight: 'bold',
    },
    cardCornerBottom: {
        position: 'absolute',
        bottom: 5,
        right: 5,
        fontSize: 14,
        fontWeight: 'bold',
        transform: [{ rotate: '180deg' }],
    },
    cardCenter: {
        fontSize: 30,
    },
    cardSuit: {
        fontSize: 14,
    },
    pointsBadge: {
        position: 'absolute',
        bottom: -10,
        right: -10,
        backgroundColor: '#333',
        width: 30,
        height: 30,
        borderRadius: 15,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#FFD700',
    },
    pointsText: {
        color: '#FFF',
        fontSize: 12,
        fontWeight: 'bold',
    },
    betContainer: {
        position: 'absolute',
        bottom: -10,
        left: 20,
        backgroundColor: '#333',
        paddingVertical: 3,
        paddingHorizontal: 8,
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#FFD700',
    },
    betText: {
        color: '#FFF',
        fontSize: 12,
        marginLeft: 5,
    },
    resultBadge: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: [{ translateX: -40 }, { translateY: -15 }, { rotate: '-15deg' }],
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 5,
        borderWidth: 2,
    },
    wonBadge: {
        backgroundColor: 'rgba(0, 255, 0, 0.7)',
        borderColor: '#00CC00',
    },
    lostBadge: {
        backgroundColor: 'rgba(255, 0, 0, 0.7)',
        borderColor: '#CC0000',
    },
    drawBadge: {
        backgroundColor: 'rgba(0, 0, 255, 0.7)',
        borderColor: '#0000CC',
    },
    resultText: {
        color: '#FFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
    },
    modalContent: {
        width: '85%',
        backgroundColor: '#2A2A2A',
        borderRadius: 12,
        padding: 20,
        borderWidth: 1,
        borderColor: '#FFD700',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#FFD700',
        marginBottom: 10,
        textAlign: 'center',
    },
    betRange: {
        color: '#FFF',
        fontSize: 14,
        textAlign: 'center',
        marginBottom: 20,
    },
    inputContainer: {
        marginBottom: 16,
    },
    inputLabel: {
        color: '#FFF',
        fontSize: 16,
        marginBottom: 8,
    },
    input: {
        backgroundColor: '#333',
        color: '#FFF',
        borderRadius: 8,
        padding: 12,
        fontSize: 16,
        borderWidth: 1,
        borderColor: '#FFD700',
    },
    modalButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 20,
    },
    modalButton: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: 12,
        borderRadius: 8,
        marginHorizontal: 5,
    },
    cancelButton: {
        backgroundColor: '#444',
        borderWidth: 1,
        borderColor: '#666',
    },
    cancelButtonText: {
        color: '#FFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
    confirmButton: {
        backgroundColor: '#FFD700',
    },
    confirmButtonText: {
        color: '#000',
        fontSize: 16,
        fontWeight: 'bold',
    },
    disabledButton: {
        opacity: 0.6,
    },
    dealerBusted: {
        backgroundColor: 'rgba(255, 0, 0, 0.7)',
        borderColor: '#CC0000',
    },
    dealerStand: {
        backgroundColor: 'rgba(0, 0, 255, 0.7)',
        borderColor: '#0000CC',
    }
});