import { StyleSheet, Dimensions, Platform } from 'react-native';
import { COLORS } from '../../constants/colors';

const { width: screenWidth } = Dimensions.get('window');
const cardWidth = (screenWidth - 45) / 2;

export default StyleSheet.create({
    container: {
        flex: 1,
        width: '100%',
        height: '100%',
    },
    gradient: {
        flex: 1,
    },
    safeArea: {
        flex: 1,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.2)',
        marginBottom: 10,
        gap: 15,
    },
    backButton: {
        padding: 8,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#a67c52',
    },
    backIcon: {
        color: '#a67c52',
    },
    battleCounter: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#a67c52',
    },
    battleCounterText: {
        color: '#a67c52',
        fontWeight: 'bold',
        marginLeft: 10,
        fontSize: 18,
    },
    playersList: {
        paddingHorizontal: 12,
        paddingTop: 8,
    },
    playerCard: {
        backgroundColor: 'rgba(20,20,20,0.9)',
        marginBottom: 10,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#a67c52',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.7,
        shadowRadius: 4,
        elevation: 5,
        flex: 1,
        margin: 6,
        maxWidth: cardWidth,
    },
    playerHeader: {
        alignItems: 'center',
        padding: 10,
    },
    playerAvatar: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#2e2b25',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#a67c52',
        marginBottom: 8,
    },
    playerInfo: {
        alignItems: 'center',
    },
    playerName: {
        color: '#FFF',
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: 4,
    },
    playerClass: {
        color: '#CCC',
        fontSize: 14,
        marginTop: 4,
    },
    challengeButton: {
        backgroundColor: '#2e2b25',
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#a67c52',
        marginTop: 10,
        minWidth: 100,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    challengeButtonDisabled: {
        opacity: 0.7,
        backgroundColor: '#1a1814',
    },
    challengeButtonText: {
        color: '#a67c52',
        fontSize: 14,
        fontWeight: 'bold',
    },
    challengeButtonPressed: {
        backgroundColor: '#a67c52',
    },
    challengeButtonTextPressed: {
        color: '#2e2b25',
    },
    emptyContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(20,20,20,0.9)',
        marginTop: 20,
        marginHorizontal: 15,
        padding: 30,
        borderWidth: 1,
        borderColor: '#a67c52',
        borderRadius: 10,
    },
    emptyText: {
        color: COLORS.white,
        fontSize: 18,
        fontWeight: 'bold',
        textAlign: 'center',
        marginTop: 15,
    },
    emptySubtext: {
        color: '#CCC',
        fontSize: 15,
        textAlign: 'center',
        marginTop: 8,
        marginBottom: 20,
    },
    centerContent: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    refreshButton: {
        backgroundColor: '#2e2b25',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: '#a67c52',
        marginTop: 15,
    },
    refreshButtonText: {
        color: '#a67c52',
        fontWeight: 'bold',
        fontSize: 16,
    },
    statsContainer: {
        flexDirection: 'column',
        alignItems: 'center',
        gap: 3,
    },
    statBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(46, 43, 37, 0.8)',
        paddingVertical: 3,
        paddingHorizontal: 6,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: 'rgba(166,124,82,0.3)',
    },
    statText: {
        color: '#a67c52',
        fontSize: 11,
        marginLeft: 4,
    },
    arenaMenu: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        paddingVertical: 10,
        paddingHorizontal: 5,
        paddingBottom: Platform.OS === 'ios' ? 34 : 10,
        backgroundColor: '#1f1a13',
        borderTopWidth: 2,
        borderColor: '#a67c52',
    },
    menuItem: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 50,
        height: 55,
        padding: 5,
    },
    menuIcon: {
        width: 24,
        height: 24,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 4,
    },
    menuText: {
        color: '#a67c52',
        fontSize: 9,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    menuItemActive: {
        opacity: 0.6,
    },
});
